version: "3.9"

services:
  db:
    image: postgres
    restart: "on-failure"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
  web:
    restart: "on-failure"
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

volumes:
  postgres_data: