version: "3.9"

services:
  nginx:
    build: ./nginx
    ports:
      - 1337:80
    depends_on:
      - web
  db:
    image: postgres:13.0-alpine
    restart: "on-failure"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
  web:
    restart: "on-failure"
    build: .
    command: gunicorn kiberone_tutor.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
      - static:/app/assets
      - media:/app/media
    expose:
      - 8000
    env_file:
      - .env
    depends_on:
      - db

volumes:
  postgres_data:
  static:
  media: