# Generated by Django 3.2.3 on 2021-08-22 04:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Удалено')),
                ('time', models.CharField(choices=[('1', '11:00'), ('2', '13:30'), ('3', '16:00'), ('4', '18:30')], default=('1', '11:00'), max_length=1, verbose_name='Время')),
                ('location', models.CharField(choices=[('1', 'КЮЧ1'), ('2', 'КЮЧ2'), ('3', 'Дзержинского'), ('4', 'Шеронова')], default=('1', 'КЮЧ1'), max_length=1, verbose_name='Локация')),
                ('day_of_week', models.CharField(choices=[('mn', 'Понедельник'), ('tu', 'Вторник'), ('we', 'Среда'), ('th', 'Четверг'), ('fr', 'Пятница'), ('st', 'Суббота'), ('sn', 'Воскресенье')], default=('mn', 'Понедельник'), max_length=2, verbose_name='День недели')),
                ('tutor', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
                'db_table': 'group',
                'unique_together': {('time', 'location', 'day_of_week')},
            },
        ),
        migrations.CreateModel(
            name='Kiberon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievement', models.CharField(choices=[('visit', 'Посещение урока'), ('eyes', 'Разминка глаз'), ('fastest', 'Быстрее всех завершил задание'), ('homework', 'За выполнение домашнего задания'), ('instagram', 'За пост в instagram'), ('social', 'За посты в соц. сети'), ('custom', 'Свое достижение')], default=('visit', 'Посещение урока'), max_length=10, unique=True, verbose_name='Достижение')),
                ('value', models.PositiveSmallIntegerField(default=5, verbose_name='Количество киберонов')),
            ],
            options={
                'verbose_name': 'Печать',
                'verbose_name_plural': 'Печати',
                'db_table': 'kiberon',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Удалено')),
                ('name', models.CharField(max_length=50, verbose_name='Фамилия Имя')),
                ('kiberon_amount', models.PositiveIntegerField(default=0)),
                ('info', models.TextField(blank=True, max_length=250, verbose_name='Информация')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='mainapp.group', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Студент',
                'verbose_name_plural': 'Студенты',
                'db_table': 'student',
            },
        ),
        migrations.CreateModel(
            name='KiberonStudentReg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата')),
                ('custom_kiberons', models.PositiveSmallIntegerField(default=0, verbose_name='Свое количество киберонов')),
                ('kiberon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.kiberon', verbose_name='Достижение')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.student', verbose_name='Студент')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Тьютор')),
            ],
            options={
                'verbose_name': 'Запись о печати',
                'verbose_name_plural': 'Записи о печатях',
                'db_table': 'kiberon_register',
                'ordering': ('-date',),
            },
        ),
    ]
