# Generated by Django 3.2.3 on 2021-09-17 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kiberonstudentreg',
            name='custom_achievement',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Кастомное достижение'),
        ),
        migrations.AlterField(
            model_name='kiberon',
            name='achievement',
            field=models.CharField(choices=[('visit', 'Посещение урока'), ('eyes', 'Разминка глаз'), ('fastest', 'Быстрее всех завершил задание'), ('homework', 'За выполнение домашнего задания'), ('instagram', 'За пост в instagram'), ('social', 'За посты в соц. сети'), ('answer', 'За ответ в конце урока'), ('custom', 'Свое достижение'), ('behavior', 'Прошел модуль без замечаний по поведению'), ('help', 'Помог другу'), ('assist', 'Помог ассистенту с уборкой'), ('rule', 'Придумал полезное правило для школы')], default=('visit', 'Посещение урока'), max_length=10, unique=True, verbose_name='Достижение'),
        ),
        migrations.AlterField(
            model_name='student',
            name='kiberon_amount',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество киберонов'),
        ),
    ]
