# Generated by Django 3.2.3 on 2021-06-06 23:20

from django.db import migrations


def create_default_settings(apps, schema_editor):
    """
    Создание настроек по умолчанию
    """
    SiteConfiguration = apps.get_model('mainapp', 'SiteConfiguration')
    try:
        times = '''11:00\n
                13:30\n
                16:00\n
                18:30'''
        locations = '''КЮЧ1\n
                       КЮЧ2\n
                       Дзержинского\n
                       Шеронова
                    '''
        kiberons = '''Посещение урока - 10\n
                      Быстрее всех завершил задание - 10\n
                      Прошел модуль без замечаний по поведению - 10\n
                      Придумал правило для КиберШколы - 10\n
                      Помог другу разобраться с заданием - 5\n
                      За победу - 10\n
                      Помог ассистенту с уборкой - 5\n
                      Победа в конкурсе, олимпиаде - 5\n
                      За тщательное выполнение гимнастики для глаз - 5\n
                      Написал(а) отзыв в соцсетях - 15\n
                      Хорошо выполнил домашнее задание - 5\n
                      Сделал пост в Instagram об обучении в КиберШколе - 15
                    '''
        SiteConfiguration.objects.create(times=times, locations=locations, kiberons=kiberons)
    except Exception:
        pass


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_default_settings)
    ]
