# Generated by Django 3.2.3 on 2021-05-31 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20210531_1120'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='kiberonstudentreg',
            unique_together=set(),
        ),
    ]
