# Generated by Django 3.2.3 on 2021-09-17 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20210917_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='visited_date',
            field=models.DateField(default=None, null=True, verbose_name='Последняя дата посещения'),
        ),
    ]
