# Generated by Django 3.2.3 on 2021-09-04 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_student_kiberon_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kiberon',
            name='achievement',
            field=models.CharField(choices=[('visit', 'Посещение урока'), ('eyes', 'Разминка глаз'), ('fastest', 'Быстрее всех завершил задание'), ('homework', 'За выполнение домашнего задания'), ('instagram', 'За пост в instagram'), ('social', 'За посты в соц. сети'), ('answer', 'За ответ в конце урока'), ('custom', 'Свое достижение')], default=('visit', 'Посещение урока'), max_length=10, unique=True, verbose_name='Достижение'),
        ),
    ]
