# Generated by Django 3.2.3 on 2021-09-04 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_kiberon_achievement'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='kiberonstudentreg',
            unique_together={('student', 'kiberon', 'date')},
        ),
    ]
