# Generated by Django 3.2.3 on 2021-05-31 02:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_kiberonstudentreg_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kiberonstudentreg',
            options={'ordering': ('-date',), 'verbose_name': 'Запись о печати', 'verbose_name_plural': 'Записи о печатях'},
        ),
        migrations.AlterField(
            model_name='kiberonstudentreg',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата'),
        ),
    ]
