# Generated by Django 3.2.3 on 2021-09-22 13:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0004_auto_20210922_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='temporary_tutor',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='temp_tutor', to=settings.AUTH_USER_MODEL, verbose_name='Временный тьютор'),
        ),
    ]
