# Generated by Django 3.2.3 on 2021-11-14 08:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_alter_group_temporary_tutor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kiberonstudentreg',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата'),
        ),
    ]
