# Generated by Django 3.2.3 on 2021-11-14 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_alter_kiberonstudentreg_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='gmail_name',
            field=models.EmailField(blank=True, default=None, max_length=70, null=True, verbose_name='Gmail'),
        ),
    ]
