# Generated by Django 3.2.3 on 2021-12-13 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_student_gmail_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fair_is_active', models.BooleanField(default=False, verbose_name='Ярмарка запущена')),
            ],
            options={
                'verbose_name': 'Настройки сайта',
            },
        ),
    ]
