# Generated by Django 3.2.6 on 2022-02-11 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_alter_student_visited_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_one', models.CharField(choices=[(1, '11'), (2, '8'), (3, '3'), (4, 'Нет верных вариантов')], max_length=50, verbose_name='a = 3<br>b = a<br>a = a + 80чему равно b?')),
                ('question_two', models.CharField(choices=[(1, '3'), (2, '-1'), (3, '7'), (4, '4')], max_length=50, verbose_name='a = 3<br>b = a + 1<br>если a > b:<br>    вывод(a + b)<br>иначе:    вывод(a - b)<br>каким будет вывод?')),
                ('question_three', models.CharField(choices=[(1, '3'), (2, '-2'), (3, '1'), (4, '8')], max_length=50, verbose_name='a = 3<br>b = a<br>a = a + 80чему равно b?')),
                ('question_four', models.CharField(choices=[(1, 'Строка текст'), (2, 'строка текста'), (3, 'истина'), (4, 'ложь')], max_length=50, verbose_name='a = 3<br>b = a<br>a = a + 80чему равно b?')),
                ('question_five', models.CharField(choices=[(1, '20'), (2, '30'), (3, '40'), (4, '50')], max_length=50, verbose_name='a = 3<br>b = a<br>a = a + 80чему равно b?')),
            ],
        ),
    ]
