# Generated by Django 3.2.6 on 2022-09-18 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_alter_student_visited_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Удалено')),
                ('address', models.CharField(blank=True, max_length=128, null=True, verbose_name='Адрес локации')),
                ('short_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Краткое наименование')),
            ],
            options={
                'verbose_name': 'Локация',
                'verbose_name_plural': 'Локации',
            },
        ),
        migrations.AddField(
            model_name='student',
            name='gmail_password',
            field=models.CharField(blank=True, default=None, max_length=30, null=True, verbose_name='Gmail password (выводить только в админке)'),
        ),
        migrations.AlterField(
            model_name='group',
            name='location',
            field=models.CharField(choices=[('1', 'КЮЧ1'), ('2', 'КЮЧ2'), ('3', 'Дзержинского'), ('4', 'Шеронова')], default=('1', 'КЮЧ1'), max_length=1, null=True, verbose_name='Локация'),
        ),
        migrations.AlterField(
            model_name='group',
            name='time',
            field=models.CharField(choices=[('1', '11:00'), ('2', '13:30'), ('3', '16:00'), ('4', '18:30')], default=('1', '11:00'), max_length=1, null=True, verbose_name='Время'),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Фамилия Имя'),
        ),
        migrations.CreateModel(
            name='AvailableTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Удалено')),
                ('time_start', models.TimeField(verbose_name='Время начала урока')),
                ('time_end', models.TimeField(verbose_name='Время завершения урока')),
            ],
            options={
                'verbose_name': 'Доступное время',
                'verbose_name_plural': 'Доступное время',
                'unique_together': {('time_start', 'time_end')},
            },
        ),
        migrations.AddField(
            model_name='group',
            name='available_location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.location', verbose_name='Локация'),
        ),
        migrations.AddField(
            model_name='group',
            name='available_time',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.availabletime', verbose_name='Время'),
        ),
    ]
