# Generated by Django 3.2.6 on 2022-02-11 02:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_test'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='test',
            options={'verbose_name': 'Результат теста', 'verbose_name_plural': 'Результаты тестов'},
        ),
        migrations.AddField(
            model_name='test',
            name='correct_answers',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='test',
            name='question_five',
            field=models.CharField(choices=[(1, '20'), (2, '30'), (3, '40'), (4, '50')], default=(1, '20'), max_length=50, verbose_name='a = 3<br>b = a<br>a = a + 80чему равно b?'),
        ),
        migrations.AlterField(
            model_name='test',
            name='question_four',
            field=models.CharField(choices=[(1, 'Строка текст'), (2, 'строка текста'), (3, 'истина'), (4, 'ложь')], default=(1, 'Строка текст'), max_length=50, verbose_name='a = 3<br>b = a<br>a = a + 80чему равно b?'),
        ),
        migrations.AlterField(
            model_name='test',
            name='question_one',
            field=models.CharField(choices=[(1, '11'), (2, '8'), (3, '3'), (4, 'Нет верных вариантов')], default=(1, '11'), max_length=50, verbose_name='a = 3<br>b = a<br>a = a + 8<br>чему равно b?'),
        ),
        migrations.AlterField(
            model_name='test',
            name='question_three',
            field=models.CharField(choices=[(1, '3'), (2, '-2'), (3, '1'), (4, '8')], default=(1, '3'), max_length=50, verbose_name='a = 3<br>b = a<br>a = a + 80чему равно b?'),
        ),
        migrations.AlterField(
            model_name='test',
            name='question_two',
            field=models.CharField(choices=[(1, '3'), (2, '-1'), (3, '7'), (4, '4')], default=(1, '3'), max_length=50, verbose_name='a = 3<br>b = a + 1<br>если a > b:<br>&nbsp;&nbsp;&nbsp;&nbsp;вывод(a + b)<br>иначе:<br>&nbsp;&nbsp;&nbsp;&nbsp;вывод(a - b)<br>каким будет вывод?'),
        ),
    ]
