# Generated by Django 3.2.6 on 2022-12-11 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_auto_20220918_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Фамилия Имя'),
        ),
        migrations.AlterUniqueTogether(
            name='group',
            unique_together={('available_time', 'available_location', 'day_of_week')},
        ),
        migrations.RemoveField(
            model_name='group',
            name='location',
        ),
        migrations.RemoveField(
            model_name='group',
            name='time',
        ),
    ]
