# Generated by Django 3.2.3 on 2022-02-12 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_auto_20220211_1225'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
