# Generated by Django 3.2.6 on 2022-12-19 07:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_auto_20221211_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kiberonstudentreg',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата'),
        ),
    ]
