# Generated by Django 3.2.6 on 2022-12-25 07:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_alter_kiberonstudentreg_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='max_custom_kiberons',
            field=models.PositiveSmallIntegerField(default=20, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Максимальное количество добавляемых/удаляемых киберонов'),
        ),
    ]
