# Generated by Django 3.2.6 on 2023-01-16 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_siteconfiguration_max_custom_kiberons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='mainapp.group', verbose_name='Группа'),
        ),
    ]
