# Generated by Django 3.2.6 on 2023-01-16 08:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0015_alter_student_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kiberonstudentreg',
            name='tutor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Тьютор'),
        ),
    ]
