# Generated by Django 3.2.6 on 2023-01-30 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0016_alter_kiberonstudentreg_tutor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kiberonstudentreg',
            options={'ordering': ('-id', '-date'), 'verbose_name': 'Запись о печати', 'verbose_name_plural': 'Записи о печатях'},
        ),
    ]
