# Generated by Django 3.2.6 on 2023-01-27 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='dark_theme_enabled',
            field=models.BooleanField(default=False, verbose_name='Темная тема включена'),
        ),
    ]
