# Generated by Django 3.2.3 on 2022-02-13 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField(blank=True, max_length=500, null=True, verbose_name='Текст ответа')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Является верным ответом')),
            ],
            options={
                'verbose_name': 'Ответ',
                'verbose_name_plural': 'Ответы',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(max_length=500, verbose_name='Текст вопроса')),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'Один правильный ответ'), (2, 'Несколько правильных ответов'), (3, 'Развернутый ответ')], default=(1, 'Один правильный ответ'), verbose_name='Тип вопроса')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Название теста')),
                ('corrects_to_pass', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Количество правильных ответов для прохождения')),
                ('questions', models.ManyToManyField(blank=True, related_name='tests', to='test.Question', verbose_name='Вопросы')),
            ],
            options={
                'verbose_name': 'Тест',
                'verbose_name_plural': 'Тесты',
            },
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testees_name', models.CharField(max_length=70, verbose_name='Имя тестируемого')),
                ('correct_count', models.PositiveSmallIntegerField(default=0, null=True, verbose_name='Количество верных ответов')),
                ('passed', models.BooleanField(default=False, verbose_name='Тест пройден')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата прохождения')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test.test', verbose_name='Тест')),
            ],
            options={
                'verbose_name': 'Результат теста',
                'verbose_name_plural': 'Результаты тестов',
            },
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='test.answer', verbose_name='Ответ пользователя')),
                ('test_result', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='test.testresult', verbose_name='Тест')),
            ],
            options={
                'verbose_name': 'Ответ пользователя',
                'verbose_name_plural': 'Ответы пользователей',
            },
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answers', to='test.question', verbose_name='Вопрос'),
        ),
    ]
