# Generated by Django 3.2.3 on 2022-02-18 13:20

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='test_type',
            field=models.CharField(choices=[('required', 'Обязательный'), ('optional', 'не обязательный')], default='required', max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=ckeditor.fields.RichTextField(max_length=500, verbose_name='Текст вопроса'),
        ),
    ]
