# Generated by Django 3.2.6 on 2023-01-16 08:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0016_alter_kiberonstudentreg_tutor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('test', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.student', verbose_name='Ученик'),
        ),
        migrations.AddField(
            model_name='testresult',
            name='tutor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Тьютор'),
        ),
    ]
