# Generated by Django 3.2.3 on 2022-02-18 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0002_auto_20220218_2320'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswer',
            name='answer_text',
            field=models.TextField(null=True, verbose_name='Развернутый ответ'),
        ),
    ]
