# Generated by Django 3.2.3 on 2022-02-19 19:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0003_useranswer_answer_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='available_for_retest',
            field=models.BooleanField(default=True, verbose_name='Возможность перепрохождения теста'),
        ),
        migrations.AddField(
            model_name='test',
            name='days_for_retest',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)], verbose_name='Количество дней для возможности перепрохождения (1-7)'),
        ),
        migrations.AlterField(
            model_name='test',
            name='test_type',
            field=models.CharField(choices=[('required', 'Обязательный'), ('optional', 'Не обязательный')], default='required', max_length=8, null=True, verbose_name='Тип теста'),
        ),
    ]
