# Generated by Django 3.2.3 on 2021-11-28 12:14

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mainapp', '0007_student_gmail_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='FairRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.student', verbose_name='Ученик')),
            ],
            options={
                'verbose_name': 'Запись о ярмарке для ученика',
                'verbose_name_plural': 'Записи о ярмарке для учеников',
            },
        ),
        migrations.CreateModel(
            name='Souvenir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Удалено')),
                ('name', models.CharField(max_length=100, verbose_name='Имя сувенира')),
                ('image', models.ImageField(blank=True, null=True, upload_to='fair_souvenirs', verbose_name='Фото сувенира')),
                ('price', models.DecimalField(decimal_places=0, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3000)], verbose_name='Стоимость в киберонах')),
            ],
            options={
                'verbose_name': 'Сувенир',
                'verbose_name_plural': 'Сувениры',
                'ordering': ('price',),
            },
        ),
        migrations.CreateModel(
            name='FairRegistrationSouvenir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fair_registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fair.fairregistration', verbose_name='Запесь о ярмарке')),
                ('souvenir', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fair.souvenir', verbose_name='Сувенир')),
            ],
            options={
                'verbose_name': 'Сувенир в записи о ярмарке',
                'verbose_name_plural': 'Сувениры в запясях о ярмарках',
            },
        ),
    ]
