# Generated by Django 3.2.3 on 2021-12-12 09:56

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_student_gmail_name'),
        ('fair', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fairregistrationsouvenir',
            name='price',
            field=models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=4, verbose_name='Стоимость в киберонах в день ярмарки'),
        ),
        migrations.AlterField(
            model_name='fairregistration',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='mainapp.student', verbose_name='Ученик'),
        ),
        migrations.AlterField(
            model_name='fairregistrationsouvenir',
            name='fair_registration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='souvenirs', to='fair.fairregistration', verbose_name='Запесь о ярмарке'),
        ),
        migrations.AlterField(
            model_name='souvenir',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3500)], verbose_name='Стоимость в киберонах'),
        ),
    ]
