# Generated by Django 3.2.3 on 2021-12-21 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fair', '0002_auto_20211212_1956'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='souvenir',
            options={'ordering': ('price', 'amount'), 'verbose_name': 'Сувенир', 'verbose_name_plural': 'Сувениры'},
        ),
        migrations.AddField(
            model_name='souvenir',
            name='amount',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='Количество'),
        ),
    ]
