# Generated by Django 3.2.6 on 2021-12-26 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fair', '0003_auto_20211222_0201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fairregistrationsouvenir',
            name='fair_registration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='souvenirs', to='fair.fairregistration', verbose_name='Запись о ярмарке'),
        ),
    ]
