# Generated by Django 3.2.6 on 2022-12-25 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fair', '0005_refund'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='refund',
            options={'verbose_name': 'Возврат', 'verbose_name_plural': 'Возвраты'},
        ),
        migrations.AlterField(
            model_name='refund',
            name='complete',
            field=models.BooleanField(default=False, editable=False, verbose_name='Возврат завершен'),
        ),
    ]
